<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Financeiro.Api</RootNamespace>
    <UserSecretsId>leovincifinance-financeiro-api</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Financeiro.Application\Financeiro.Application.csproj" />
    <ProjectReference Include="..\Financeiro.Infrastructure\Financeiro.Infrastructure.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\BuildingBlocks.Common\BuildingBlocks.Common.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\BuildingBlocks.WebHost\BuildingBlocks.WebHost.csproj" />
  </ItemGroup>

</Project>
